const styles = {
    page: {
        minHeight: "100vh",
        background: "#fafbfc",
        display: "flex",
        justifyContent: "center",
        padding: "100px 24px 60px",
    },
    container: {
        maxWidth: "480px",
        width: "100%",
    },
    header: {
        textAlign: "center",
        marginBottom: "32px",
    },
    logoIcon: {
        fontSize: "36px",
        marginBottom: "8px",
    },
    title: {
        fontSize: "26px",
        fontWeight: "800",
        color: "#0f172a",
        margin: "0 0 6px",
        letterSpacing: "-0.5px",
    },
    subtitle: {
        fontSize: "15px",
        color: "#64748b",
        margin: 0,
        lineHeight: 1.6,
    },
    tabs: {
        display: "flex",
        gap: "10px",
        marginBottom: "24px",
    },
    tab: {
        flex: 1,
        padding: "12px",
        border: "1.5px solid #e2e8f0",
        borderRadius: "12px",
        background: "#fff",
        color: "#64748b",
        fontSize: "14px",
        fontWeight: "600",
        cursor: "pointer",
        transition: "all 0.2s cubic-bezier(0.33,1,0.68,1)",
    },
    tabActive: {
        background: "linear-gradient(135deg, #22c55e 0%, #16a34a 100%)",
        borderColor: "transparent",
        color: "#fff",
        boxShadow: "0 4px 12px -2px rgba(22,163,74,0.3)",
    },
    uploadArea: { marginBottom: "24px" },
    uploadLabel: { cursor: "pointer", display: "block" },
    uploadBox: {
        border: "2px dashed #d1d5db",
        borderRadius: "16px",
        padding: "48px 20px",
        textAlign: "center",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "10px",
        background: "#fafbfc",
        transition: "all 0.3s ease",
    },
    uploadIcon: { fontSize: "40px", color: "#94a3b8" },
    uploadText: { color: "#475569", fontSize: "15px", fontWeight: "600" },
    uploadHint: { color: "#94a3b8", fontSize: "12px" },
    cameraArea: { marginBottom: "24px", textAlign: "center" },
    video: { width: "100%", borderRadius: "16px", border: "1px solid #e2e8f0" },
    captureBtn: {
        width: "64px", height: "64px", borderRadius: "50%",
        border: "3px solid #16a34a", background: "transparent",
        cursor: "pointer", marginTop: "16px",
        display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 0,
        transition: "all 0.2s ease",
    },
    captureBtnInner: {
        width: "48px", height: "48px", borderRadius: "50%",
        backgroundColor: "#dc2626",
    },
    cameraPlaceholder: {
        border: "2px dashed #d1d5db", borderRadius: "16px",
        padding: "60px 20px", color: "#94a3b8", textAlign: "center", background: "#fafbfc",
    },
    previewContainer: { textAlign: "center", marginBottom: "24px" },
    previewLabel: { color: "#64748b", fontSize: "13px", marginBottom: "10px", fontWeight: "600" },
    previewImg: {
        width: "100%", maxHeight: "300px", objectFit: "cover",
        borderRadius: "16px", border: "1px solid #e2e8f0",
        boxShadow: "0 4px 12px -4px rgba(0,0,0,0.06)",
    },
    actions: { textAlign: "center", marginBottom: "24px" },
    detectBtn: {
        width: "100%", padding: "16px", border: "none", borderRadius: "14px",
        background: "linear-gradient(135deg, #22c55e 0%, #16a34a 100%)",
        color: "#fff", fontSize: "16px",
        fontWeight: "700", cursor: "pointer",
        boxShadow: "0 6px 16px -4px rgba(22,163,74,0.3)",
        transition: "all 0.3s cubic-bezier(0.33,1,0.68,1)",
    },
    detectBtnDisabled: { opacity: 0.5, cursor: "not-allowed" },
    resultContainer: {
        background: "#fff", borderRadius: "20px",
        border: "1px solid rgba(0,0,0,0.04)", padding: "28px", marginTop: "12px",
        boxShadow: "0 8px 24px -8px rgba(0,0,0,0.06)",
        animation: "fadeInUp 0.5s cubic-bezier(0.33,1,0.68,1)",
    },
    resultHeader: { textAlign: "center", marginBottom: "24px" },
    resultTitle: { color: "#0f172a", fontSize: "20px", margin: 0, fontWeight: "800", letterSpacing: "-0.3px" },
    resultCards: { display: "flex", gap: "12px", marginBottom: "24px" },
    resultCard: {
        flex: 1, background: "#fafbfc", borderRadius: "14px",
        padding: "18px", display: "flex", flexDirection: "column",
        alignItems: "center", gap: "6px", border: "1px solid rgba(0,0,0,0.03)",
        transition: "all 0.2s ease",
    },
    cardIcon: { fontSize: "22px", marginBottom: "4px" },
    cardLabel: {
        color: "#64748b", fontSize: "11px", textTransform: "uppercase",
        letterSpacing: "0.8px", fontWeight: "700",
    },
    cardValue: { color: "#0f172a", fontSize: "15px", fontWeight: "700", textAlign: "center" },
    progressBar: {
        width: "100%", height: "6px", background: "#e2e8f0",
        borderRadius: "4px", marginTop: "8px", overflow: "hidden",
    },
    progressFill: { height: "100%", borderRadius: "4px", transition: "width 0.8s cubic-bezier(0.33,1,0.68,1)" },
    penangananSection: { marginBottom: "24px" },
    penangananTitle: { color: "#166534", fontSize: "16px", fontWeight: "800", marginBottom: "14px", letterSpacing: "-0.3px" },
    penangananCard: {
        display: "flex", gap: "14px", alignItems: "flex-start",
        background: "linear-gradient(135deg, #f0fdf4, #dcfce7)", border: "1px solid #bbf7d0",
        borderRadius: "14px", padding: "16px", marginBottom: "10px",
        transition: "all 0.2s ease",
    },
    penangananNumber: {
        minWidth: "32px", height: "32px", borderRadius: "50%",
        background: "linear-gradient(135deg, #22c55e, #16a34a)", color: "#fff",
        display: "flex", alignItems: "center", justifyContent: "center",
        fontWeight: "700", fontSize: "14px", flexShrink: 0,
        boxShadow: "0 3px 8px -2px rgba(22,163,74,0.3)",
    },
    penangananContent: { flex: 1 },
    penangananJudul: { color: "#0f172a", fontWeight: "700", fontSize: "15px", margin: "0 0 4px" },
    penangananDesc: { color: "#475569", fontSize: "14px", margin: 0, lineHeight: 1.6 },
    resetBtn: {
        width: "100%", padding: "14px", border: "1.5px solid #e2e8f0",
        borderRadius: "12px", background: "#fff", color: "#475569",
        fontSize: "14px", fontWeight: "600", cursor: "pointer",
        transition: "all 0.2s ease",
    },
    footer: { textAlign: "center", color: "#94a3b8", fontSize: "12px", marginTop: "40px" },
};

export default styles;
